import type { Metadata } from "next";
import "@/sass/main.scss"
import Header from "@/app/layouts/Headers/Header";
import Footer from "@/app/layouts/Footers/Footer";

export const metadata: Metadata = {
  title: "My blog",
  description: "Generated by my blog",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
